cache:
  mount:
    - /drone/sundials-3.1.1
    - /drone/sundials-3.1.1-nolapack
    - /drone/sundials-2.7.0-nolapack
build:
  image: bjodah/bjodahimg18dev:v1.2
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
  commands:
    - git fetch -tq  # used by ``git describe``
    - if [ ! -d /drone/sundials-3.1.1 ]; then .ci/get_sundials.sh 3.1.1 /drone/sundials-3.1.1 -DLAPACK_ENABLE:BOOL=ON -DSUNDIALS_INDEX_TYPE:STRING="int32_t"; fi
    - if [ ! -d /drone/sundials-3.1.1-nolapack ]; then .ci/get_sundials.sh 3.1.1 /drone/sundials-3.1.1-nolapack -DLAPACK_ENABLE:BOOL=OFF; fi
    - if [ ! -d /drone/sundials-2.7.0-nolapack ]; then .ci/get_sundials.sh 2.7.0 /drone/sundials-2.7.0-nolapack -DLAPACK_ENABLE:BOOL=OFF; fi
    - .ci/run_ci.sh pycvodes /drone/sundials-3.1.1
    - .ci/run_ci.sh pycvodes /drone/sundials-3.1.1-nolapack
    - .ci/run_ci.sh pycvodes /drone/sundials-2.7.0-nolapack
    - apt-get update --quiet && apt-get install --quiet -y libsundials-dev
    - .ci/run_ci.sh pycvodes /usr
    - PYCVODES_LAPACK="" .ci/run_ci.sh pycvodes /drone/sundials-3.1.1
    - PYCVODES_LAPACK="" .ci/run_ci.sh pycvodes /usr
    - python3 -m pip install --user -e .[docs]
    - python3 -m pytest --pep8
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - apt-get remove -qq -y libsundials-dev
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
    - bash -c '[[ $(python3 setup.py --version 2>/dev/null) =~ ^[0-9]+.* ]]'

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pycvodes
    source: deploy/
    target: ~
    recursive: true
    delete: false
