clone:
  depth: 2
  recursive: true
  submodule_override:
    external/anyode: git://github.com/bjodah/anyode.git
build:
  image: bjodah/bjodahimg20dot:2.1.0.4
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-11/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
    - PYCVODES_STRICT=1
    - CPATH=/usr/include/suitesparse
    - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    - CC=gcc-10
    - CXX=g++-10
  commands:
    - git fetch -tq  # used by ``git describe``
    - PYCVODES_NO_LAPACK=1 PYCVODES_NO_KLU=1 .ci/run_ci.sh pycvodes /opt/sundials-5.4.0-noklu-nolapack-extended-int64
    - PYCVODES_NO_LAPACK=1 PYCVODES_NO_KLU=1 LOW_PRECISION=1 .ci/run_ci.sh pycvodes /opt/sundials-5.4.0-noklu-nolapack-single-int32
    # sundials is underlinked...
    - LDFLAGS="-llapack -lblas" BUILD_DOCS=1 .ci/run_ci.sh pycvodes /opt/sundials-5.4.0-klu-lapack
    - ./scripts/prepare_deploy.sh
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
    - bash -c '[[ $(python3 setup.py --version 2>/dev/null) =~ ^[0-9]+.* ]]'

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pycvodes
    source: deploy/
    target: ~
    recursive: true
    delete: false
