clone:
  depth: 2
  recursive: true
  submodule_override:
    external/anyode: git://github.com/bjodah/anyode.git
cache:
  mount:
      # changing int type used for index only available in 3.1+
      # changing real type available in both 2.7 and 3.1
      # HOWEVER lapack and some of the stuff compiled with sundials (KLU, arkODE, etc.) don't like this
      # so skip fiddling wih realtype, inttype except in 3.1 and sans lapack, klu, etc.
      - /drone/sun-3.2.1-lapack-klu
      - /drone/sun-3.2.1-nolapack-klu
      - /drone/sun-3.2.1-lapack-noklu
      - /drone/sun-3.2.1-nolapack-noklu
      - /drone/sun-2.7.0-lapack-klu
      - /drone/sun-2.7.0-nolapack-klu
      - /drone/sun-2.7.0-lapack-noklu
      - /drone/sun-2.7.0-nolapack-noklu
      - /drone/sun-3.2.1-nolapack-noklu-extended-int64
      - /drone/sun-3.2.1-nolapack-noklu-extended-int32
      - /drone/sun-3.2.1-nolapack-noklu-single-int64
      - /drone/sun-3.2.1-nolapack-noklu-single-int32
      - /drone/sun-4.0.2-lapack-klu
      - /drone/sun-4.0.2-nolapack-klu
      - /drone/sun-4.0.2-lapack-noklu
      - /drone/sun-4.0.2-nolapack-noklu
      - /drone/sun-4.0.2-nolapack-noklu-extended-int64
      - /drone/sun-4.0.2-nolapack-noklu-extended-int32
      - /drone/sun-4.0.2-nolapack-noklu-single-int64
      - /drone/sun-4.0.2-nolapack-noklu-single-int32
build:
  image: bjodah/bjodahimg18:v1.5
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
    - PYCVODES_STRICT=1
  commands:
    - git fetch -tq  # used by ``git describe``
    - export C_INCLUDE_PATH=/usr/include/suitesparse CPLUS_INCLUDE_PATH=/usr/include/suitesparse LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    - if [ ! -d /drone/sun-3.2.1-lapack-klu ]; then .ci/get_sundials.sh 3.2.1 /drone/sun-3.2.1-lapack-klu -DLAPACK_ENABLE:BOOL=ON -DKLU_ENABLE:BOOL=ON -DSUNDIALS_INDEX_TYPE:STRING="int32_t" -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu; fi
    - if [ ! -d /drone/sun-3.2.1-nolapack-klu ]; then .ci/get_sundials.sh 3.2.1 /drone/sun-3.2.1-nolapack-klu -DLAPACK_ENABLE:BOOL=OFF -DKLU_ENABLE:BOOL=ON -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu; fi
    - if [ ! -d /drone/sun-3.2.1-lapack-noklu ]; then .ci/get_sundials.sh 3.2.1 /drone/sun-3.2.1-lapack-noklu -DLAPACK_ENABLE:BOOL=ON -DKLU_ENABLE:BOOL=OFF -DSUNDIALS_INDEX_TYPE:STRING="int32_t"; fi
    - if [ ! -d /drone/sun-3.2.1-nolapack-noklu ]; then .ci/get_sundials.sh 3.2.1 /drone/sun-3.2.1-nolapack-noklu -DLAPACK_ENABLE:BOOL=OFF -DKLU_ENABLE:BOOL=OFF; fi
    - if [ ! -d /drone/sun-2.7.0-lapack-klu ]; then .ci/get_sundials.sh 2.7.0 /drone/sun-2.7.0-lapack-klu -DLAPACK_ENABLE:BOOL=ON -DKLU_ENABLE:BOOL=ON -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu; fi
    - if [ ! -d /drone/sun-2.7.0-nolapack-klu ]; then .ci/get_sundials.sh 2.7.0 /drone/sun-2.7.0-nolapack-klu -DLAPACK_ENABLE:BOOL=OFF -DKLU_ENABLE:BOOL=ON -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu; fi
    - if [ ! -d /drone/sun-2.7.0-lapack-noklu ]; then .ci/get_sundials.sh 2.7.0 /drone/sun-2.7.0-lapack-noklu -DLAPACK_ENABLE:BOOL=ON -DKLU_ENABLE:BOOL=OFF; fi
    - if [ ! -d /drone/sun-2.7.0-nolapack-noklu ]; then .ci/get_sundials.sh 2.7.0 /drone/sun-2.7.0-nolapack-noklu -DLAPACK_ENABLE:BOOL=OFF -DKLU_ENABLE:BOOL=OFF; fi
    - if [ ! -d /drone/sun-3.2.1-nolapack-noklu-extended-int64 ]; then .ci/get_sundials.sh 3.2.1 /drone/sun-3.2.1-nolapack-noklu-extended-int64  -DSUNDIALS_INDEX_TYPE:STRING="int64_t"  -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_PRECISION:STRING="extended"; fi
    - if [ ! -d /drone/sun-3.2.1-nolapack-noklu-extended-int32 ]; then .ci/get_sundials.sh 3.2.1 /drone/sun-3.2.1-nolapack-noklu-extended-int32  -DSUNDIALS_INDEX_TYPE:STRING="int32_t"  -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_PRECISION:STRING="extended"; fi
    - if [ ! -d /drone/sun-3.2.1-nolapack-noklu-single-int64 ]; then .ci/get_sundials.sh 3.2.1 /drone/sun-3.2.1-nolapack-noklu-single-int64  -DSUNDIALS_INDEX_TYPE:STRING="int64_t"  -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_PRECISION:STRING="single"; fi
    - if [ ! -d /drone/sun-3.2.1-nolapack-noklu-single-int32 ]; then .ci/get_sundials.sh 3.2.1 /drone/sun-3.2.1-nolapack-noklu-single-int32  -DSUNDIALS_INDEX_TYPE:STRING="int32_t" -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_PRECISION:STRING="single"; fi
    - if [ ! -d /drone/sun-4.0.2-lapack-klu ]; then .ci/get_sundials.sh 4.0.2 /drone/sun-4.0.2-lapack-klu -DLAPACK_ENABLE:BOOL=ON -DKLU_ENABLE:BOOL=ON -DSUNDIALS_INDEX_SIZE=32 -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu; fi
    - if [ ! -d /drone/sun-4.0.2-nolapack-klu ]; then .ci/get_sundials.sh 4.0.2 /drone/sun-4.0.2-nolapack-klu -DLAPACK_ENABLE:BOOL=OFF -DKLU_ENABLE:BOOL=ON -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu; fi
    - if [ ! -d /drone/sun-4.0.2-lapack-noklu ]; then .ci/get_sundials.sh 4.0.2 /drone/sun-4.0.2-lapack-noklu -DLAPACK_ENABLE:BOOL=ON -DKLU_ENABLE:BOOL=OFF -DSUNDIALS_INDEX_SIZE=32; fi
    - if [ ! -d /drone/sun-4.0.2-nolapack-noklu ]; then .ci/get_sundials.sh 4.0.2 /drone/sun-4.0.2-nolapack-noklu -DLAPACK_ENABLE:BOOL=OFF -DKLU_ENABLE:BOOL=OFF; fi
    - if [ ! -d /drone/sun-4.0.2-nolapack-noklu-extended-int64 ]; then .ci/get_sundials.sh 4.0.2 /drone/sun-4.0.2-nolapack-noklu-extended-int64  -DSUNDIALS_INDEX_SIZE=64  -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_PRECISION:STRING="extended"; fi
    - if [ ! -d /drone/sun-4.0.2-nolapack-noklu-extended-int32 ]; then .ci/get_sundials.sh 4.0.2 /drone/sun-4.0.2-nolapack-noklu-extended-int32  -DSUNDIALS_INDEX_SIZE=32  -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_PRECISION:STRING="extended"; fi
    - if [ ! -d /drone/sun-4.0.2-nolapack-noklu-single-int64 ]; then .ci/get_sundials.sh 4.0.2 /drone/sun-4.0.2-nolapack-noklu-single-int64  -DSUNDIALS_INDEX_SIZE=64  -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_PRECISION:STRING="single"; fi
    - if [ ! -d /drone/sun-4.0.2-nolapack-noklu-single-int32 ]; then .ci/get_sundials.sh 4.0.2 /drone/sun-4.0.2-nolapack-noklu-single-int32  -DSUNDIALS_INDEX_SIZE=32 -DKLU_ENABLE:BOOL=OFF -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_PRECISION:STRING="single"; fi
    - python3 -m pip install --upgrade pip
    - .ci/run_ci.sh pycvodes /drone/sun-3.2.1-lapack-klu
    - .ci/run_ci.sh pycvodes /drone/sun-3.2.1-nolapack-klu
    - .ci/run_ci.sh pycvodes /drone/sun-3.2.1-lapack-noklu
    - .ci/run_ci.sh pycvodes /drone/sun-3.2.1-nolapack-noklu
    - .ci/run_ci.sh pycvodes /drone/sun-2.7.0-lapack-klu
    - .ci/run_ci.sh pycvodes /drone/sun-2.7.0-nolapack-klu
    - .ci/run_ci.sh pycvodes /drone/sun-2.7.0-lapack-noklu
    - .ci/run_ci.sh pycvodes /drone/sun-2.7.0-nolapack-noklu
    - .ci/run_ci.sh pycvodes /drone/sun-3.2.1-nolapack-noklu-extended-int64
    - .ci/run_ci.sh pycvodes /drone/sun-3.2.1-nolapack-noklu-extended-int32
    - LOW_PRECISION=1 .ci/run_ci.sh pycvodes /drone/sun-3.2.1-nolapack-noklu-single-int32
    - LOW_PRECISION=1 .ci/run_ci.sh pycvodes /drone/sun-3.2.1-nolapack-noklu-single-int64
    - TEST_NATIVE_CLANG=0 PYCVODES_LAPACK="" .ci/run_ci.sh pycvodes /drone/sun-3.2.1-nolapack-klu
    - .ci/run_ci.sh pycvodes /drone/sun-4.0.2-lapack-klu
    - .ci/run_ci.sh pycvodes /drone/sun-4.0.2-nolapack-klu
    - .ci/run_ci.sh pycvodes /drone/sun-4.0.2-lapack-noklu
    - .ci/run_ci.sh pycvodes /drone/sun-4.0.2-nolapack-noklu
    - .ci/run_ci.sh pycvodes /drone/sun-4.0.2-nolapack-noklu-extended-int64
    - .ci/run_ci.sh pycvodes /drone/sun-4.0.2-nolapack-noklu-extended-int32
    - LOW_PRECISION=1 .ci/run_ci.sh pycvodes /drone/sun-4.0.2-nolapack-noklu-single-int32
    - LOW_PRECISION=1 .ci/run_ci.sh pycvodes /drone/sun-4.0.2-nolapack-noklu-single-int64
    - TEST_NATIVE_CLANG=0 PYCVODES_LAPACK="" .ci/run_ci.sh pycvodes /drone/sun-4.0.2-nolapack-klu
    - unset C_INCLUDE_PATH CPLUS_INCLUDE_PATH LD_LIBRARY_PATH
    - apt-get remove -qq -y libsuitesparse-dev
    - apt-get update --quiet && apt-get install --quiet -y libsundials-dev
    - python3 -m pip install wurlitzer
    - unset PYCVODES_STRICT
    - .ci/run_ci.sh pycvodes /usr
    - TEST_NATIVE_CLANG=1 PYCVODES_LAPACK="" .ci/run_ci.sh pycvodes /usr
    - git clean -xfd
    - python3 -m pip install --user -e .[docs]
    - python3 -m pytest --pep8 --cov $PKG_NAME --cov-report html
    - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
    - python3 setup.py sdist
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - apt-get remove -qq -y libsundials-dev
    # - PATH=/opt/miniconda3/bin:$PATH conda update --quiet conda-build
    # - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
    - bash -c '[[ $(python3 setup.py --version 2>/dev/null) =~ ^[0-9]+.* ]]'

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pycvodes
    source: deploy/
    target: ~
    recursive: true
    delete: false
