cache:
  mount:
    - /drone/sundials-3.1.1

build:
  image: bjodah/bjodahimg18dev:v1.2
  environment:
    - PYCVODES_LAPACK=lapack,blas
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
  commands:
    - git fetch -tq  # used by ``git describe``
    - if [ ! -d /drone/sundials-3.1.1 ]; then .ci/get_sundials-3.1.1.sh /drone/sundials-3.1.1; fi
    - CPATH=/drone/sundials-3.1.1/include LIBRARY_PATH=/drone/sundials-3.1.1/lib LD_LIBRARY_PATH=/drone/sundials-3.1.1/lib ./scripts/ci.sh pycvodes
    - python3 -m pip uninstall --yes pycvodes
    - rm -r /usr/local/lib/python*/dist-packages/pycvodes*  # pip uninstall is useless
    - apt-get update --quiet
    - apt-get install --quiet -y libsundials-dev
    - git clean -xfd
    - ./scripts/ci.sh pycvodes    
    - python3 -m pip install --user -e .[docs]
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - apt-get remove -qq -y libsundials-dev
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
    - bash -c '[[ $(python3 setup.py --version 2>/dev/null) =~ ^[0-9]+.* ]]'

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pycvodes
    source: deploy/
    target: ~
    recursive: true
    delete: false
