cache:
  mount:
    - /drone/sundials-3.2.1
    - /drone/sundials-3.2.1-nolapack
    - /drone/sundials-2.7.0-nolapack
build:
  image: bjodah/bjodahimg18:v1.5
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
  commands:
    - git fetch -tq  # used by ``git describe``
    - if [ ! -d /drone/sundials-3.2.1 ]; then .ci/get_sundials.sh 3.2.1 /drone/sundials-3.2.1 -DLAPACK_ENABLE:BOOL=ON -DSUNDIALS_INDEX_SIZE=32; fi
    - if [ ! -d /drone/sundials-3.2.1-nolapack ]; then .ci/get_sundials.sh 3.2.1 /drone/sundials-3.2.1-nolapack -DLAPACK_ENABLE:BOOL=OFF; fi
    - if [ ! -d /drone/sundials-2.7.0-nolapack ]; then .ci/get_sundials.sh 2.7.0 /drone/sundials-2.7.0-nolapack -DLAPACK_ENABLE:BOOL=OFF; fi
    - python3 -m pip install wurlitzer
    - .ci/run_ci.sh pycvodes /drone/sundials-3.2.1
    - .ci/run_ci.sh pycvodes /drone/sundials-3.2.1-nolapack
    - .ci/run_ci.sh pycvodes /drone/sundials-2.7.0-nolapack
    - apt-get update --quiet && apt-get install --quiet -y libsundials-dev
    - .ci/run_ci.sh pycvodes /usr
    - TEST_NATIVE_CLANG=0 PYCVODES_LAPACK="" .ci/run_ci.sh pycvodes /drone/sundials-3.2.1
    - TEST_NATIVE_CLANG=1 PYCVODES_LAPACK="" .ci/run_ci.sh pycvodes /usr
    - python3 -m pip install --user -e .[docs]
    - curl -Ls https://bootstrap.pypa.io/get-pip.py | python2 - --user
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - python2 -m pip install --user --upgrade --upgrade-strategy only-if-needed . pytest
    - python2 -m pytest && python2 -m doctest README.rst
    - apt-get remove -qq -y libsundials-dev
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
    - bash -c '[[ $(python3 setup.py --version 2>/dev/null) =~ ^[0-9]+.* ]]'

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pycvodes
    source: deploy/
    target: ~
    recursive: true
    delete: false
