when:
  - event: [pull_request, tag, cron, push]

steps:
  - name: pypy
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:16
    commands:
      - .ci/test-case.sh --python /opt-3/pypy3.10-v7.3.15-linux64/bin/python3 /opt-3/sundials-6.7.0-debug

  - name: py3.11-dbg
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:16
    commands:
      - .ci/test-case.sh --python /opt-3/cpython-v3.11.?-debug/bin/python3 /opt-3/sundials-6.7.0-debug

  - name: py3.12-dbg
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:16
    commands:
      - .ci/test-case.sh --python /opt-3/cpython-v3.12.2-debug/bin/python3 /opt-3/sundials-6.7.0-debug

  - name: py3.11-extended
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:16
    environment:
      - PYCVODES_NO_LAPACK=1
      - PYCVODES_NO_KLU=1
    commands:
      - .ci/test-case.sh --python /opt-3/cpython-v3.11-apt-deb/bin/python3 /opt-3/sundials-6.7.0-extended

  - name: py3.12-single
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:16
    environment:
      - PYCVODES_NO_LAPACK=1
      - PYCVODES_NO_KLU=1
    commands:
      - .ci/test-case.sh --python /opt-3/cpython-v3.12.2-release/bin/python3 /opt-3/sundials-6.7.0-single


  - name: sdist-and-docs
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:16
    environment:
      - PYCVODES_STRICT=1
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    commands:
      #- git fetch -tq
      # - bash -c '[[ $(python3 setup.py --version 2>/dev/null) =~ ^[0-9]+.* ]]'
      - .ci/test-sdist.sh
      - ./scripts/prepare_deploy.sh
      - if grep "DO-NOT-MERGE!" -R . --exclude ".woodpecker.yaml"; then exit 1; fi
    depends_on:
      - pypy
      - py3.11-dbg
      - py3.12-dbg
      - py3.11-extended
      - py3.12-single

  - name: deploy-public-html
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:16
    commands:
      - tar -C ./deploy/public_html czf pycovdes-${CI_COMMIT_BRANCH}.tar.gz .
      - curl -T pycovdes-${CI_COMMIT_BRANCH}.tar.gz ftp://pycovdes:$${ARTIFACTS_PASS}@$${FTP_SERVER}/public_html/
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: github.com/bjodah/pycovdes
    depends_on:
      - sdist-and-docs
