when:
  - event: [push]  # pull_request, tag, cron, 

steps:
  - name: pypy
    image: cont-reg.bjodah.se:443/bjodah/triceratops-4:16
    commands:
      - .ci/test-case.sh --tmp --python /opt-3/pypy3.10-v7.3.*-linux64/bin/python3 /opt-3/sundials-6.7.0-debug

  - name: py3.12-dbg
    image: cont-reg.bjodah.se:443/bjodah/triceratops-4:16
    commands:
      - .ci/test-case.sh --tmp --python /opt-3/cpython-v3.12.?-debug/bin/python3 /opt-3/sundials-6.7.0-debug

  - name: py3.13-dbg
    image: cont-reg.bjodah.se:443/bjodah/triceratops-4:16
    commands:
      - .ci/test-case.sh --tmp --python /opt-3/cpython-v3.13.?-debug/bin/python3 /opt-3/sundials-6.7.0-debug

  - name: py3.12-extended
    image: cont-reg.bjodah.se:443/bjodah/triceratops-4:16
    environment:
      - PYCVODES_NO_LAPACK=1
      - PYCVODES_NO_KLU=1
    commands:
      - bash -c "source /opt-3/cpython-v3.12-apt-deb/bin/activate; .ci/test-case.sh --tmp /opt-3/sundials-6.7.0-extended"

  - name: py3.11-single
    image: cont-reg.bjodah.se:443/bjodah/triceratops-4:16
    environment:
      - PYCVODES_NO_LAPACK=1
      - PYCVODES_NO_KLU=1
    commands:
      - .ci/test-case.sh --tmp --python /opt-3/cpython-v3.11.*-release/bin/python3 /opt-3/sundials-6.7.0-single

  - name: sdist-and-docs
    image: cont-reg.bjodah.se:443/bjodah/triceratops-4:16
    environment:
      - PYCVODES_STRICT=1
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    commands:
      #- git fetch -tq
      # - bash -c '[[ $(python3 setup.py --version 2>/dev/null) =~ ^[0-9]+.* ]]'
      - .ci/test-sdist.sh
      - ./scripts/prepare_deploy.sh
      - if grep "DO-NOT-MERGE!" -R . --exclude ".woodpecker.yaml"; then exit 1; fi
    depends_on:
      - pypy
      - py3.12-dbg
      - py3.13-dbg
      - py3.12-extended
      - py3.11-single

  - name: deploy-public-html
    image: cont-reg.bjodah.se:443/bjodah/triceratops-4:16
    commands:
      - tar -C ./deploy/public_html -czf pycvodes-${CI_COMMIT_BRANCH}.tar.gz .
      - curl -T pycvodes-${CI_COMMIT_BRANCH}.tar.gz ftp://pycvodes:$${ARTIFACTS_PASS}@$${FTP_SERVER}/public_html/
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: bjodah/pycvodes
    depends_on:
      - sdist-and-docs
