[build-system]
requires = ["setuptools", "wheel", "Cython", "scikit-build", "cmake", "ninja"]
build-backend = "setuptools.build_meta"

[tool.scikit-build]
cmake.args = [
    "-DCMAKE_BUILD_TYPE=Release",
]
wheel.packages = ["pycovdes"]
