[build-system]
requires = ["setuptools", "wheel", "cython", "scikit-build", "cmake", "ninja", "numpy", "cython-cmake"]
build-backend = "setuptools.build_meta"

[tool.scikit-build]
cmake.args = [
    "-DCMAKE_BUILD_TYPE=Release",
]
wheel.packages = ["pycvodes"]
