package:
    name: pycvodes
    version: 0.4.0.git

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - python
        - numpy
        - sundials
        - cython
    run:
        - python
        - numpy
        - sundials

test:
    imports:
        - pycvodes
    requires:
        - pytest
    commands:
        - py.test --pyargs pycvodes

about:
    home: https://github.com/bjodah/pycvodes
    license: BSD
