package:
  name: pycvodes
  version: 0.4.0.git

source:
  path: ../

build:
  number: 0

requirements:
  build:
   - python
   - numpy
   - sundials
   - cython
  run:
   - python
   - numpy
   - sundials

test:
    imports:
        - pycvodes
    # requires:
    #     - pytest
    # commands:
    #     - py.test --pyargs pycvodes  # https://github.com/conda/conda/issues/2075, https://github.com/pytest-dev/pytest/issues/1445

about:
    home: https://github.com/bjodah/pycvodes
    license: BSD
