{% set name = "pycvodes" %}
{% set version = "0.11.0.dev0+git" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 200
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - toolchain
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20*  # [not win]
    - sundials
    - python
    - setuptools
    - pip
    - cython
    - numpy 1.11.*
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - sundials
    - python
    - numpy >=1.11

test:
  imports:
    - pycvodes
  requires:
    - pytest

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python wrapper around cvodes (from the sundials library)'
  doc_url: https://bjodah.github.io/{{ name }}/latest


extra:
  recipe-maintainers:
    - bjodah
